### ISSUE TITLE
Usage of Wire library.

### ISSUE THREAD

**Issue by Koepel** [Atlas-Scientific/Ezo_I2c_lib#1]
In the file "Ezo_I2c_lib/Ezo_i2c.cpp" in the function "receive_cmd()" the reading and writing is mixed.
I don't know what that code is trying to do. Is it only to read data, without setting a register address ? Then the `Wire.beginTransmission()` and `Wire.endTransmission()` should not be there.

See the [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes) and also my [alternative explanation of the functions of the Wire library](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Explanation-of-the-functions-of-the-Wire-library).

**Comment by Atlas-Scientific** [comment]
Gotcha! Its fixed in the latest commit.
