### ISSUE TITLE
Compile Failure

### ISSUE THREAD

**Issue by JonGordon123** [Atlas-Scientific/Ezo_I2c_lib#13]
Was getting an error while trying to compile with Arduino IDE 1.8.15.

Had to add 
`case Ezo_board::NOT_READ_CMD:`
`Serial.print("No Command ");    //no command`
`break;`
to switch statement in "print_success_or_error" in Ezo_i2c_util.cpp

**Comment by Atlas-Scientific** [comment]
Should be fixed by PR #23
