### ISSUE TITLE
Wrong comments, likely copy-pasted

### ISSUE THREAD

**Issue by clarkwinkelmann** [Atlas-Scientific/Ezo_I2c_lib#2]
I noticed the following comments do not seem to match the code they describe. Looks like they were copy-pasted from the pH examples and not updated.

https://github.com/Atlas-Scientific/Ezo_I2c_lib/blob/541195c2fadeaf0fdaafed6ca5f0e230020e0090/Examples/temp_comp_example/temp_comp_example.ino#L4

https://github.com/Atlas-Scientific/Ezo_I2c_lib/blob/541195c2fadeaf0fdaafed6ca5f0e230020e0090/Examples/temp_comp_rt_example/temp_comp_rt_example.ino#L4

**Comment by Atlas-Scientific** [comment]
Thank you. The comments were corrected.
